@startuml

state "Door Open" as Door_Open
Door_Open : entry / light_on
Door_Open : exit / light_off
state "Door Closed" as Door_Closed {
   state Baking
   Baking : entry / heating_on
   Baking : exit / heating_off
   state Off
   [*] --> Off
}
[*] --> Door_Closed
Door_Open --> Door_Closed[H] : close
Baking --> Off : off
Off --> Baking : bake
Door_Closed --> Door_Open : open[not broken]
Door_Closed --> [*] : open[broken] / dying

@enduml
