@startuml

state "Door Open" as Door_Open
Door_Open : entry / light_on
Door_Open : exit / light_off
state "Door Closed" as Door_Closed {
   state Heating
   Heating : entry / heating_on
   Heating : exit / heating_off
   state Off
   [*] --> Off
}
[*] --> Door_Closed
Door_Open --> Door_Closed[H] : close
Heating --> Off : off
Off --> Heating : bake
Door_Closed --> Door_Open : open[not broken]
Door_Closed --> [*] : open[broken] / dying

@enduml
